# Operações matemáticas

***DISCLAIMER: Este notebook foi escrito com base no que li [neste](https://docs.julialang.org/en/v1/manual/mathematical-operations/) capítulo do manual***

Bem aqui não vou falar das operações básicas mas sim daquilo que é novidade para mim.

Começando por `//` que no Python simplesmente remove os valores decimais.

Aqui em Julia `//` é o mesmo que o traço de fração: $\frac{numerador}{denominador}$, ou seja, podemos criar racionais.

Além disso, Julia já transforma as frações na sua forma irredutível.

In [2]:
# 6//4 vai virar 3//2, pois é a sua forma irredutível
6//4

3//2

In [3]:
typeof(6//4)

Rational{Int64}

## Operadores Bitwise

Eu não uso muito os operadores bitwise (costumo usar mais o booleanos: `||`,`&&` e `!`), mas há 2 operadores que me chamaram a atenção.

O XOR definido por `\xor+TAB` e o shift lógico `>>>` diferente do shift aritmético à direita `>>`.

Para diferenciar os o shift lógico do aritmético, gostei da resposta escolhida [aqui](https://stackoverflow.com/questions/44694957/the-difference-between-logical-shift-right-arithmetic-shift-right-and-rotate-r).

É sempre bom lembrar que shift aritmético à esquerda é o mesmo que multiplicar o número por 2. Já o shift aritmético à direita é o mesmo que dividir o número por 2.


***Nota: Operações bitwise só funcionam com inteiros!***

In [4]:
x = 3

# é o mesmo que x * 2
println( x << 1)

# é o mesmo que x * 2 * 2
println( x << 2)

# é o mesmo que x * 2 * 2 * 2
println( x << 3)

6
12
24


In [5]:
x = 12

# é o mesmo que x / 2
println( x >> 1)

# é o mesmo que x / 2 / 2
println( x >> 2)

# é o mesmo que x / 2 / 2 / 2, 
# só que aqui a parte decimal é descartada devido a só se trabalhar com inteiros
println( x >> 3)

6
3
1


## Operações elemento a elemento


Muitas vezes vamos querer fazer certas operações dentro de arrays e matrizes, por exemplo, fazer o quadrado de todos os elementos de um array. Elevar um array ao quadrado vai disparar um erro, pois matematicamente não faz sentido.

Porém há algo denominado de *broadcasting*. Isto é, ele pega, neste caso, em um escalar ou número e faz uma dada operação, que neste caso é a exponenciação, em cada elemento do array.

`[1,2,3,4] .^ 2` == `[1^2, 2^2, 3^2, 4^2]`


O `.` antes de uma operação  siginfica *broadcasting*, também é chamada de "dot call".

In [6]:
x = [1,2,3,4]

x .^ 4

4-element Vector{Int64}:
   1
  16
  81
 256

In [7]:
M = [
    
    [1,2],
    [2,3],
    [4,5]
]

3-element Vector{Vector{Int64}}:
 [1, 2]
 [2, 3]
 [4, 5]

In [8]:
v = [ [1,2] ]

1-element Vector{Vector{Int64}}:
 [1, 2]

In [9]:
# Broadcasting entre uma matriz 3x2 e array 1x2
# Temos de ter o mesmo número de linhas ou o mesmo número de colunas
M .+ v

3-element Vector{Vector{Int64}}:
 [2, 4]
 [3, 5]
 [5, 7]

Para verem como o broadcasting é bom demais, imaginem esta expressão:

$2 \cdot A^2 + \sin {A}, A \in \mathbb{R}^{m \times n}$

Já estão a imaginar o loop que vão ter de fazer para aplicar todas as aritméticas a cada elemente da matriz $A$ ... Pois é, não vai ser preciso, pois esta sintaxe "dos pontos" `.` (prefiro chamar de broadcasting), pode ser aninhada! Ficaria algo deste género:

`2 .* A.^2 .+ sin.(A)`


Também podem usar o `@.` ele converte todas as operações de uma expressão em broadcasting:

`@. 2A^2 + sin(A)`

## Comparações com Números decimais "especiais"

Os nossos amigos `Floats` comportam-se da mesma forma que os inteiros, porém `Inf`, `-Inf` e `NaN` são Floats e têm um comportamento um pouco diferente ... Na realidade o `NaN` é que tem um comportamento diferente.

* Comecemos pelos: 0.0 e -0.0, que são iguais mas 0.0 NÃO é maior que -0.0
* Inf é maior que qualquer coisa, exceto NaN
* -Inf é menor que qualquer coisa, exceto NaN
* As comparações com NaN são sempre falsas, incluindo com ele mesmo!


Bem isto do `NaN` é estranho, mas gostaria que pensassem um pouco no seu significado ...
NaN significa ***Not a Number*** (em português, Não é um Número) e agora pensem, quantas coisas podem não ser um número? Várias! Eu não sou um número (para o governo sou, mas esqueçamos isso), o meu quarto não é um número, o planeta não é um número!

Ao dizermos `NaN` podemos estar-nos a referir a qualquer coisa que não é um número, e Julia não sabe, pois só referimo-nos a *NaN*.

In [10]:
NaN == NaN

false

Caso queiram verificar se algo é infinito ou finito:

In [11]:
# Verificar se número é finito
isfinite(2.133333)

true

In [12]:
# Verificar se número é infinito
isinf(-Inf)

true

Também podem saber se algo é NaN.

In [13]:
isnan(NaN)

true

E caso tenham 2 arrays iguais, porém com NaNs dentro, se compararem com `==` vai dar falso, porque como explicado acima `NaN != NaN`. MAS, Julia tem uma função que realmente verifica a semalhança entre 2 objetos (mesmo que tenham NaNs).

Ela consegue fazer essa verificação, pois em background ela faz um hash de cada objeto e isso dará hashes diferentes caso haja realmente valores diferentes, se não os hashes serão iguais e, consequentemente, retornará um `true`.

In [14]:
[23,34,NaN] == [23,34,NaN]

false

In [17]:
# Função que verifica se 2 objetos, neste caso arrays, são iguais
isequal([23,34,NaN], [23,34,NaN])

true

Gostava de referir um operador de comparação que eu acho super útil, o aproximadamente: $\approx$

Ele verifica se 2 valores são aproximados

In [16]:
println( 0.1 + 0.2 )

# Pelo resultado acima vimos que não é bem igual a 0.3
println( 0.1 + 0.2 == 0.3)

# Mas é beeeemmm próximo, certo?
println( 0.1 + 0.2 ≈ 0.3)

0.30000000000000004
false
true


## Cadeia de comparações

Podemos encadear várias comparações sem recorrer ao operador boolean0 `&&` ou, em caso de comparações elemento a elemento, ao operador bitwise `&`.

In [18]:
3 == 3 > 2 >= 1 == 1

true

Funciona também com broadcasting

In [45]:
a = [0.999, 0.0001]

# Verificar se todos os elementos do array estão no intervalo ]0,1[
0 .< a .< 1

2-element BitVector:
 1
 1

A ordem das comparações ***Não é certa***

In [24]:
f(x) = (println(x); x)

f(1) < f(2) <= f(3)

2
1
3


true

Para controlar a ordem, deve-se usar explicitamente o  operador `&&`

In [25]:
f(1) < f(2) && f(2) <= f(3)

1
2
2
3


true

## Precedências e associatividades

Não vou criar aqui uma tabela com as precedências com cada operador, pois isso já está disponível [aqui](https://docs.julialang.org/en/v1/manual/mathematical-operations/#Operator-Precedence-and-Associativity).

Porém todos os operadores que estão no `Base` da Julia, podem ser passados para o método `operator_precedence` e assim podemos saber o nível da precedência.

***Nota: Quanto maior o número maior precedência***

In [26]:
# Precedencia do operador +
Base.operator_precedence(:+)

11

In [27]:
# Precedencia do operador *
Base.operator_precedence(:*)

12

Além da precedência, podemos verificar a associatividade de cada operador. A associatividade, diz-nos onde o operador precisa ser colocado, por exemplo, eu não posso colocar o `^` (operador de exponenciação) à esquerda do escalar ou da variável, a associatividade dele é à direita: `x ^ 2`.

Já o operador + posso colocar à esquerda do número, à direita do número ou entre 2 números, ou seja, não há uma associatividade.

In [29]:
# Associatividade do operador ^
Base.operator_associativity(:^)

:right

In [31]:
# Associatividade do operador +
Base.operator_associativity(:+)

:none

In [32]:
# Associatividade do operador -
Base.operator_associativity(:-)

:left

## Conversões

Julia tem 3 tipos de conversões possíveis:
* O mais comum é chamar a função com o nome do `Type`, por exemplo: `Int32(42)`
    * Também pode-se usar o método `convert(Type, variável)`
* Pode-se usar o módulo: `x % T` - em que `T` é o `Type` que vai converter o **inteiro** `x` em outro inteiro do tipo `T` (caso o inteiro não dê para armazenar no tipo que queremos, os bits "a mais" serão removidos, mudando o valor de x)
* As funções do tipo `round(Type, variable)` também podem converter valores (além de arrendonda-los primeiro).

In [33]:
# Converter um inteiro em um inteiro de 8 bits
UInt(127)

0x000000000000007f

In [34]:
# Converter um inteiro que não pode ser representado em 8 bits
Int8(234)

LoadError: InexactError: trunc(Int8, 234)

In [36]:
# Porém se usarmos o módulo, vai funcionar MAS o nosso valor vai ser alterado devido à truncação de bits
234 % Int8

-22

In [37]:
# Float para Inteiro com a função round
round(UInt8, 12.56)

0x0d

## Funções matemáticas

Assim como na parte de precedências, deixo [aqui](https://docs.julialang.org/en/v1/manual/mathematical-operations/#Rounding-functions) o link para o começo das diferentes listas de funções.

Vou citar algumas porque achei-as interessantes:

* Tem o `floor(T, x)` para arrendondar para baixo (-Inf) e pode levar o `Type` para converter
* Tem o `ceil(T, x)` para arrendondar para cima (Inf) e pode levar o `Type` para converter
* O `trunc(T, x)` arredonda no formato "mais comum" ( direção a 0) e também pode converter para o `Type` que quisermos


* Podemos dividir 2 valores e aplicar diretamente o `floor` ou o `ceil`, com as funções `fld(x,y)` e `cld(x,y)`.
* Tem o `div(x,y)` que faz a divisão entre 2 valores (arredonda em direção a zero).
* Temos o `rem(x,y)` que dá o nosso resto (podemos utilizar a sintaxe padrão `x % y`).
* O `gcd(x,y,...)` retorna o máximo divisor comum dos argumentos.
* O `lcm(x,y,...)` retorna o mínimo múltiplo comum dos argumentos.

* O `sign(x)` retona -1 se x é negativo, 1 se x é positivo e 0 caso x seja 0.
* Já o `signbit(x)` retorna `true` caso o bit de sinal seja 1 (ou seja, se x for negativo), se não retorna `false`.


* Tem a função exponencial (`exp(x)`), logarítmo nas diferentes bases(`log(x)` = ln, `log10(x)` = log base 10, `log2(x)` = log base 2).

***Nota: Quando precisarem de calcular logaritmos e/ou algo com a função exponencial, onde os vossos valores são extremamente pequenos, usem `expm1` e `log1p`. Caso precisem de calcular hipotenusas onde os valores dos lados do triângulo são muito grandes usem `hypot`. Se seguirem a documentação são referenciados estes 2 pequenos artigos que explicam o porquê:***

* [expm1, log1p, erfc](https://www.johndcook.com/blog/2010/06/07/math-library-functions-that-seem-unnecessary/)
* [hypot](https://www.johndcook.com/blog/2010/06/02/whats-so-hard-about-finding-a-hypotenuse/)

Temos todas as funções trignométricas, como: `sin`, `cos`, `tan`, `asin`, `acos`, `atan` - onde os resultados vêm em **radianos**.

Caso queira-se usar a representação em **graus** tem de se usar as funções com o sufixo `d`: `sind`, `cosd`, `tand`, `asind`, `acosd`, `atand` ...


***Nota: Caso queiram calcular senos e cossenos onde: $\pi \cdot x$ - usem as funções `sinpi` e `cospi`, pois são mais precisas.***