# Operações matemáticas

***DISCLAIMER: Este notebook foi escrito com base no que li [neste](https://docs.julialang.org/en/v1/manual/mathematical-operations/) capítulo do manual***

Bem aqui não vou falar das operações básicas mas sim daquilo que é novidade para mim.

Começando por `//` que no Python significa `floor()`, ou seja, simplesmente zerar as os valores decimais.

Aqui em Julia `//` é o mesmo que o traço de fração: $\frac{numerador}{denominador}$, ou seja, podemos criar racionais. 

Além disso, Julia já transforma as frações na sua forma irredutível.

In [19]:
# 6//4 vai virar 3//2, pois é a sua forma irredutível
6//4

3//2

In [20]:
typeof(6//4)

Rational{Int64}

Eu não uso muito os operadores bitwise (costumo usar mais o booleanos: `||`,`&&` e `!`), mas há 2 que me chamaram a atenção.

O XOR definido por `\xor+TAB` e o shift lógico à direita `>>>` diferente do shift aritmético à direita `>>`.

Para diferenciar os o shift lógico do aritmético, gostei da resposta escolhida [aqui](https://stackoverflow.com/questions/44694957/the-difference-between-logical-shift-right-arithmetic-shift-right-and-rotate-r)

Sempre bom lembrar que shift aritmético à esquerda é o mesmo que multiplicar o número por 2. Já o shift aritmético direito é o mesmo que dividir o número por 2.


***Nota: Operações bitwise só funcionam com inteiros!***

In [27]:
x = 3

# é o mesmo que x * 2
println( x << 1)

# é o mesmo que x * 2 * 2
println( x << 2)

# é o mesmo que x * 2 * 2 * 2
println( x << 3)

6
12
24


In [38]:
x = 12

# é o mesmo que x / 2
println( x >> 1)

# é o mesmo que x / 2 / 2
println( x >> 2)

# é o mesmo que x / 2 / 2 / 2, 
# só que aqui a parte decimal é descartada devido a só se trabalhar com inteiros
println( x >> 3)

6
3
1


## Operações elemento a elemento


Muitas vezes vamos querer fazer certas operações dentro de arrays e matrizes, por exemplo, fazer o quadrado de todos os elementos de um array. Elevar um array ao quadrado vai disparar um erro, pois matemáticamente não faz sentido.

Porém há algo denominado de *broadcasting* que basicamente é pegar, neste caso, em um escalar/número e fazer uma dada operação, neste caso exponenciação, em cada elemento do array.

`[1,2,3,4] .^ 2` == `[1^2, 2^2, 3^2, 4^2]`


O `.` antes de uma operação  siginfica *broadcasting*.

In [42]:
x = [1,2,3,4]

x .^ 4

4-element Vector{Int64}:
   1
  16
  81
 256

In [71]:
M = [
    
    [1,2],
    [2,3],
    [4,5]
]

3-element Vector{Vector{Int64}}:
 [1, 2]
 [2, 3]
 [4, 5]

In [72]:
v = [ [1,2] ]

1-element Vector{Vector{Int64}}:
 [1, 2]

In [76]:
# Broadcasting entre uma matriz 3x2 e array 1x2
# Temos de ter ou o mesmo número de linhas ou de colunas
M .+ v

3-element Vector{Vector{Int64}}:
 [2, 4]
 [3, 5]
 [5, 7]

Para verem como o broadcasting é bom demais, imaginem esta expressão:

$2 \cdot A^2 + \sin {A}, A \in \mathbb{R}^{m \times n}$

Já estão a imaginar o loop que vão ter de fazer para aplicar todas as aritméticas a cada elemente da matriz $A$ ... Pois é, não vai ser preciso, pois esta sintaxe dos pontos `.` (prefiro chamar de broadcasting), pode ser aninhada! Ficaria algo deste género:

`2 .* A.^2 .+ sin.(A)`


Também podem usar o `@.` ele converte todas as operações de uma expressão em broadcasting:

`@. 2A^2 + sin(A)`

## Comparações com Números decimais "especiais"

Os nossos amigos `Floats` comportam-se da mesma forma que os inteiros, porém `Inf`, `-Inf` e `NaN` são Floats e têm um comportamento um pouco diferente ... Na realidade o `NaN` é que tem um comportamento diferente.

* Comecemos pelos 0.0 e -0.0, são iguais mas 0.0 NÃO é maior que -0.0
* Inf é maior que qualquer coisa, exceto NaN
* -Inf é menor que qualquer coisa, exceto NaN
* As comparações com NaN são sempre falsas, incluindo com ele mesmo!


Bem isto do `NaN` é estranho, mas gostaria que pensassem um pouco no seu significado ...
NaN significa ***Not a Number*** (em português, Não é um Número) e agora pensem, quantas coisas podem não ser um número? Várias! Eu não sou um número (para o governo sou, mas esqueçamos isso), o meu quarto não é um número, o planeta não é um número!

Ao dizermos `NaN` podemos estar-nos a referir a qualquer coisa que não é um número, e Julia não sabe, pois só dissemos: NaN

In [79]:
NaN == NaN

false

Caso queiram verificar se algo é infinito ou finito:

In [84]:
# Verificar se número é finito
isfinite(2.133333)

true

In [85]:
# Verificar se número é infinito
isinf(-Inf)

true

Também podem saber se algo é NaN.

In [86]:
isnan(NaN)

true

E caso tenham 2 arrays iguais, porém com NaNs dentro, se compararem com `==` vai dar falso, porque como explicado acima `NaN != NaN`. MAS, Julia tem uma função que realmente verifica a semalhança entre 2, por exemplo.

In [87]:
[23,34,NaN] == [23,34,NaN]

false

In [89]:
# Função que verifica se 2 arrays, neste caso, são iguais
isequal([23,34,NaN], [23,34,NaN])

true

Gostava de referir um operador de comparação que eu acho super útil, o aproximadamente: $\approx$

Ele verifica se 2 valores são aproximados

In [103]:
println( 0.1 + 0.2 )

# Pelo resultado acima vimos que não é bem igual a 0.3
println( 0.1 + 0.2 == 0.3)

# Mas é beeeemmm próximo, certo?
println( 0.1 + 0.2 ≈ 0.3)

0.30000000000000004
false
true
